package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"
	"project-structure/internal/module/user/presentation/gql/generated"
)

// CheckStatus is the resolver for the checkStatus field.
func (r *mutationResolver) CheckStatus(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: CheckStatus - checkStatus"))
}

// GqlStatus is the resolver for the gqlStatus field.
func (r *queryResolver) GqlStatus(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: GqlStatus - gqlStatus"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
