Host: localhost
Port: 3000
GinMode: debug
Mongo:
  Host: localhost
  Port: 27017
  Username: root
  Password: root
  Name: test
  SSL: false
  Clustered: false
  Driver: Mongo
  Timeout: 20
Services:
  workflow: grpcs://127.0.0.1:5031
Nats:
  Url: localhost
  Port: 4222
  Topic:
    Read: auction_handler_steps
    Write: auction_handler_read

